"""empty message

Revision ID: 15ddfde7ee98
Revises: 3775a6de2892
Create Date: 2015-07-01 18:46:23.202029

"""

# revision identifiers, used by Alembic.
revision = '15ddfde7ee98'
down_revision = '3775a6de2892'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    ### end Alembic commands ###
