"""empty message

Revision ID: 16fae6b9183f
Revises: 27cb38ce6374
Create Date: 2015-11-10 08:58:06.571457

"""

# revision identifiers, used by Alembic.
revision = '16fae6b9183f'
down_revision = '27cb38ce6374'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'user', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'owner_id')
    ### end Alembic commands ###
