"""empty message

Revision ID: 1b3d6e1706f
Revises: 42277db2193a
Create Date: 2015-06-08 14:55:38.363694

"""

# revision identifiers, used by Alembic.
revision = '1b3d6e1706f'
down_revision = '42277db2193a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
