"""empty message

Revision ID: 1dc2378290f0
Revises: 3775a6de2892
Create Date: 2015-07-01 18:46:23.204869

"""

# revision identifiers, used by Alembic.
revision = '1dc2378290f0'
down_revision = '3775a6de2892'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('lists',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('raw_json', postgresql.JSON(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('lists')
    ### end Alembic commands ###
    pass
