"""empty message

Revision ID: 34472beb56d4
Revises: 494f0e1b3b07
Create Date: 2015-11-10 08:38:13.369822

"""

# revision identifiers, used by Alembic.
revision = '34472beb56d4'
down_revision = '494f0e1b3b07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
