"""empty message

Revision ID: 3775a6de2892
Revises: 9d53c99ecf7
Create Date: 2015-06-08 19:31:33.697854

"""

# revision identifiers, used by Alembic.
revision = '3775a6de2892'
down_revision = '9d53c99ecf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
