"""empty message

Revision ID: 42277db2193a
Revises: 36e8b8159d8
Create Date: 2015-06-08 14:45:52.994050

"""

# revision identifiers, used by Alembic.
revision = '42277db2193a'
down_revision = '36e8b8159d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
