"""empty message

Revision ID: 494f0e1b3b07
Revises: 2e300fdc4543
Create Date: 2015-11-05 20:43:00.451035

"""

# revision identifiers, used by Alembic.
revision = '494f0e1b3b07'
down_revision = '2e300fdc4543'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tags_name_key', 'tags', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'tags_name_key', 'tags', ['name'])
    ### end Alembic commands ###
