"""empty message

Revision ID: 5077fc856b59
Revises: 16fae6b9183f
Create Date: 2015-11-10 09:51:52.382500

"""

# revision identifiers, used by Alembic.
revision = '5077fc856b59'
down_revision = '16fae6b9183f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag_name', sa.String(length=80), nullable=False))
    op.drop_column('tags', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('tags', 'tag_name')
    ### end Alembic commands ###
