"""empty message

Revision ID: 722dc77dd3
Revises: None
Create Date: 2015-11-05 17:37:56.412148

"""

# revision identifiers, used by Alembic.
revision = '722dc77dd3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
