"""empty message

Revision ID: 9d53c99ecf7
Revises: b594e02674
Create Date: 2015-06-08 19:30:07.036269

"""

# revision identifiers, used by Alembic.
revision = '9d53c99ecf7'
down_revision = 'b594e02674'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('location', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'location')
    ### end Alembic commands ###
