"""empty message

Revision ID: f55565299f2
Revises: 3d14853510de
Create Date: 2015-06-08 19:21:33.895829

"""

# revision identifiers, used by Alembic.
revision = 'f55565299f2'
down_revision = '3d14853510de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('annotations', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('annotations', 'name')
    ### end Alembic commands ###
